version: "3"

services:
  pg:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ${DB_DATAPATH}:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: localpass
      POSTGRES_USER: postgres
      POSTGRES_DB: localdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
